# Generated by Django 2.2.6 on 2019-10-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explorer',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=100)),
                ('route_id', models.CharField(max_length=64)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'unique_together': {('route_id', 'author_email', 'date_posted')},
            },
        ),
    ]
