# Generated by Django 2.2.6 on 2019-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191017_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorer',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
