# Generated by Django 2.2.6 on 2019-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191017_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorer',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
