# Generated by Django 2.2.6 on 2019-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder_Routes',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('route_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures_of_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('poster', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Routes',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('bolt_locations', models.CharField(max_length=300)),
                ('number_of_pitches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Traditional_Routes',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('general_route_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=64)),
                ('rock_name', models.CharField(max_length=100)),
                ('park_name', models.CharField(max_length=100)),
                ('route_location_on_park', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('grade', models.CharField(max_length=5)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
            options={
                'unique_together': {('route_id', 'rock_name', 'park_name')},
            },
        ),
        migrations.CreateModel(
            name='Rocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock_name', models.CharField(max_length=100)),
                ('park_name', models.CharField(max_length=100)),
                ('rock_location_in_park', models.CharField(max_length=5000)),
            ],
            options={
                'unique_together': {('rock_name', 'park_name')},
            },
        ),
        migrations.CreateModel(
            name='Pitches',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pitch_number', models.IntegerField()),
                ('pitch_length_in_feet', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
            ],
            options={
                'unique_together': {('route_id', 'pitch_number')},
            },
        ),
    ]
