# Generated by Django 2.2.6 on 2019-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
