# Generated by Django 2.2.7 on 2019-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesapp', '0004_auto_20191130_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
