# Generated by Django 2.2.7 on 2019-12-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routesapp', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
