# Generated by Django 2.2.7 on 2019-12-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesapp', '0006_auto_20191201_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='parks',
            name='profile_picture',
            field=models.CharField(default='/media/post_images/Dawn-Wall1.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
